println("ascii: " + toNumber("a"))
println("string: " + toString(49))

println(typeOf(null) == NULL)
println(typeOf(123) == NUMBER)
println(typeOf("hi") == STRING)
println(typeOf(true) == BOOLEAN)
println(typeOf([1, 2]) == ARRAY)
println(typeOf(< >) == STRUCTURE)
println(typeOf(sort) == FUNCTION)
